class ChemparseError(Exception):
    def __init__(self, *args: object) -> None: ...

class ParenthesesMismatchError(ChemparseError):
    def __init__(self, formula: str) -> None: ...

class NestedParenthesesError(ChemparseError):
    def __init__(self, formula: str) -> None: ...

class ClosedParenthesesBeforeOpenError(ChemparseError):
    def __init__(self, formula: str) -> None: ...
