from typing import Any, Generator

def find_all(sub: str, a_str: str) -> Generator[int, Any, None]: ...
def get_first_elem(formula: str) -> tuple[str, bool]: ...
def inner_parse_formula(text: str) -> dict[str, float]: ...
def find_occurrences(s: str, ch: str) -> list[int]: ...
def parse_formula(text: str) -> dict[str, float]: ...
