from .exceptions import ClosedParenthesesBeforeOpenError as ClosedParenthesesBeforeOpenError, ParenthesesMismatchError as ParenthesesMismatchError
from typing import Any, Generator

RE_SIGNED_NUMBER: str
RE_NUMBER: str
RE_LETTERS: str

def find_all(sub: str, a_str: str) -> Generator[int, Any, None]: ...
def get_first_elem(formula: str) -> tuple[str, bool]: ...
def inner_parse_formula(text: str) -> dict[str, float]: ...
def find_occurrences(s: str, ch: str) -> list[int]: ...
def get_first_parenth_match(text: str) -> int: ...
def parse_formula(text: str) -> dict[str, float]: ...
